[project]
name = "MLOps_RecruitAIr"
version = "0.0.1"
description = "MLOps group project for good company practices in ML"
authors = [
  { name = "RecruitAIr" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "loguru",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "pip",
    "python-dotenv",
    "ruff",
    "tqdm",
    "typer",
]
requires-python = "~=3.12.0"


[tool.ruff]
line-length = 99
src = ["MLOps_RecruitAIr"]
include = ["pyproject.toml", "MLOps_RecruitAIr/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["MLOps_RecruitAIr"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pylint>=3.3.8",
    "pytest>=8.4.2",
]

